module.exports = [
  { key: 'homepage', text: '首页配置' },
  { key: 'ships', text: '船舶信息' },
  { key: 'ports', text: '港口信息' },
  { key: 'orgs', text: '公司信息' },
  { key: 'newsConfig', text: '新闻配置' },
  { key: 'news', text: '新闻' },
  { key: 'regulations', text: '法规' },
  { key: 'recommendations', text: '推荐' },
  { key: 'auditCompany', text: '审核注册公司' },
  { key: 'users', text: '用户及用户组' },
  { key: 'acc-rules', text: '访问规则' },
  { key: 'acc-roles', text: '访问身份' },
  { key: 'settings', text: '全局设置' },
  { key: 'report', text: '报表' },
];
