module.exports = {
  'PTACVAHK': require('epui-md/svg-icons/ep/products/PTACVAHK'),
  'PTCC': require('epui-md/svg-icons/ep/products/PTCC'),
  'PTCLN': require('epui-md/svg-icons/ep/products/PTCLN'),
  'PTCPD': require('epui-md/svg-icons/ep/products/PTCPD'),
  'PTCVD': require('epui-md/svg-icons/ep/products/PTCVD'),
  'PTCTM': require('epui-md/svg-icons/ep/products/PTCTM'),
  'PTEC': require('epui-md/svg-icons/ep/products/PTEC'),
  'PTSPSLGA': require('epui-md/svg-icons/ep/products/PTSPSLGA'),
  'PTISP': require('epui-md/svg-icons/ep/products/PTISP'),
  'PTOL': require('epui-md/svg-icons/ep/products/PTOL'),
  'PTOLFVSL': require('epui-md/svg-icons/ep/products/PTOLFVSL'),
  'PTOMREQ': require('epui-md/svg-icons/ep/products/PTOMREQ'),
  'PTOT': require('epui-md/svg-icons/ep/products/PTOT'),
  'PTPSCIA': require('epui-md/svg-icons/ep/products/PTPSCIA'),
  'PTPSSCE': require('epui-md/svg-icons/ep/products/PTPSSCE'),
  'PTRSCC': require('epui-md/svg-icons/ep/products/PTRSCC'),
  'PTSP': require('epui-md/svg-icons/ep/products/PTSP'),
  'PTSR': require('epui-md/svg-icons/ep/products/PTSR'),
  'PTSV': require('epui-md/svg-icons/ep/products/PTSV'),
  'PTTSA': require('epui-md/svg-icons/ep/products/PTTSA'),
  'PTVIO': require('epui-md/svg-icons/ep/products/PTVIO'),
  'PTAGT': require('epui-md/svg-icons/ep/products/PTAGT'),
  'PTOT': require('epui-md/svg-icons/ep/products/PTOT'),
  'PTSOF': require('epui-md/svg-icons/ep/products/PTSOF'),
  'UNKNOWN': require('./unknown'),
};
