module.exports = {
  ACCOUNT_TYPE: {
    CONSIGNER: 'consigner',
    CONSIGNEE: 'consignee'
  },
  SEGMENT_STATUS: {
    UNKNOWN: 0,
    ON_THE_WAY: 300,
    ARRIVED: 700,
    BERTHED: 1000,
    DEPARTURED: 1500,
    IN_ACCIDENT: 3000,
    CANCELED: -1
  },
  ORDER_ENTRY_STATUS: {
    INITIAL: 0,
    QUOTING: 100,
    QUOTED: 200,
    PRE_AUDIT_FAILED: 289,
    PRE_AUDITED: 290,
    REJECTED: 50,
    ACCEPTED: 300,
    WAITING_FOR_PENDING: 400,
    PENDING: 500,
    EXECUTING: 600,
    EXECUTED: 700,
    POST_AUDIT_FAILED: 789,
    POST_AUDITED: 790,
    BLAMED: 750,
    WAITING_FOR_COMPLETE: 800,
    CANCELLED: 999,
    COMPLETED: 1000,
  },
  ORDER_MODE: {
    CONSIGNER: 'consigner',
    CONSIGNEE: 'consignee',
    VIEWER: 'viewer',
    ADMIN: 'admin',
  },
  ORDER_STATUS: {
    INITIAL: 0,
    NORMAL: 100,
    WAITING_FOR_PAYMENT: 300,
    WAITING_FOR_REFUND: 500,
    CANCELLED: 999,
    CLOSED: 1000,
  },
  ORGANIZATION_TYPE:[
     "ORBK",
     "ORBR",
     "ORCA",
     "ORCH",
     "ORCM",
     "ORCT",
     "ORFM",
     "ORGA",
     "ORIN",
     "OROP",
     "OROW",
     "ORPG",
     "ORPS",
     "ORRC",
     "ORSH",
     "ORSM",
     "ORSO",
     "ORSP",
     "ORSR",
     "ORSV",
     "ORSY",
     "ORTD",
     "ORTM",
     "ORWS"
  ],
  ACCOUNT_MANAGEMENT: [
    'addRole',
    'editRole',
    'deleteRole',
    'addUser',
    'editUser',
    'deleteUser',
    'editProfile',
  ],
  ORDER_PERMISSION_AGENCY: [
    'startOperation',
    'completeOperation',
    'completeOrder',
    'cancelOrder',
    'quotation',
    'noticeSetting',
    'chat',
    'addService',
    'deleteService',
    'editService'
  ],
  ORDER_PERMISSION_PRINCIPAL: [
    'createOrder',
    'cancelOrder',
    'chat',
    'noticeSetting',
    'checkQuote',
    'addService',
    'deleteService',
    'editService'
  ],
};
