module.exports = {
  'Alert': require('./alert'),
  'CargoQuantityDialog': require('~/src/sections/order/add-cargo-quantity-dialog'),
  'ChangePassword': require('~/src/sections/user/changePasswordScreen'),
  'Confirm': require('./confirm'),
  'CostEstViewDialog': require('~/src/sections/order/cost-est-view-dialog'),
  'NewsEditorDialog': require('~/src/sections/news/news-edit-dialog'),
  'RegulationEditorDialog': require('~/src/sections/regulation/regulation-edit-dialog'),
  'RegulationViewDialog': require('~/src/app/regulation-dialog'),
  'HomepageEditorDialog': require('~/src/sections/homepage/homepage-edit-dialog'),
  'NewsConfigEditorDialog': require('~/src/sections/news/news-config/news-config-edit-dialog'),
  'NewsViewDialog': require('~/src/app/news-dialog'),
  'OrganizationForm': require('~/src/shared/organization-form'),
  'OrganizationViewDialog': require('~/src/app/organization-dialog'),
  'PortFormDialog': require('~/src/shared/port-form'),
  'PortViewDialog': require('~/src/app/port-dialog'),
  'RecommendationsDialog': require('~/src/app/recommendations-dialog'),
  'ShipFormCompleted': require('~/src/app/ship-dialog/ship-form-completed'),
  'ShipFormVerify': require('~/src/app/ship-dialog/ship-form-verify'),
  'ShipFormConnect': require('~/src/app/ship-dialog/ship-form-connect'),
  'ShipView': require('~/src/app/ship-dialog/ship-view'),
  'FeedbackView': require('~/src/sections/order/feedback-dialog'),
  'EditSegment': require('~/src/sections/ship/edit-segment-dialog'),
  'RegisterOrganization': require('~/src/shared/register-organization'),
};
